# .travis.yml
language: node_js
node_js:
  - "8.10.0"
before_install:
  - npm i -g npm@5.8.0
  - yarn install
branches:
  only:
    - master
email:
  on_failure: change
  on_success: never
cache:
  directories:
    - node_modules
git:
  depth: 20
script:
  - npm run prod